Updated to work with Ada Wavefile Library v2.0.0
gusthoff/ada_wavefiles_gtk_app pull request #2
Opened 2021-09-10 16:09 UTC by silentTeee

Changes also documented in CHANGELOG and README

2021-09-14 22:05 UTC, gusthoff requested changes
Thanks a lot for your contribution! Would you mind restricting the changes to the source-code file and project file? (I have no objections to those changes.)

2021-09-15 04:10 UTC, silentTeee commented
Glad to contribute! I really admire the quality of your library.

As for restricting the commit, that is okay by me, I just re-uploaded. :slightly_smiling_face:

2021-09-15 17:04 UTC, gusthoff approved these changes

2021-09-15 17:04 UTC, merged

2021-09-15 17:04 UTC, gusthoff commented
Again, thanks a lot! :-)